const db=supabase.createClient('https://hqrheypbdvhwpnwdoqka.supabase.co','sb_publishable_-YVy92hAZ_-IpNJOJTX_Sg_kQVd5_ZI'),$=s=>document.querySelector(s),today=new Date().toISOString().slice(0,10);let records=[],me,profile;
document.head.insertAdjacentHTML('beforeend','<style>body{background:radial-gradient(circle at top right,#dbeafe,#f8fafc 42%,#eff6ff)}.panel,.card,.case{box-shadow:0 8px 28px #163a5f12;border-color:#dbeafe}.top{padding:10px 0}.brand{letter-spacing:-.4px}.primary{background:linear-gradient(135deg,#2563eb,#0f4cba)}.tabs{padding:7px;background:#fff;border:1px solid #dbeafe;border-radius:14px}.tabs button{border:0}.card{background:linear-gradient(145deg,#fff,#f8fbff)}h2{letter-spacing:-.3px}</style>');
document.body.insertAdjacentHTML('afterbegin','<div id="auth" style="position:fixed;inset:0;z-index:5;background:#102a43ee;display:grid;place-items:center;padding:18px"><form id="authForm" class="panel" style="width:min(420px,100%);background:white"><h2>MVC Keşif Girişi</h2><p class="muted">Hesaplar yalnızca yönetici tarafından oluşturulur.</p><label>E-posta<input name="email" type="email" required></label><br><label>Şifre<input name="password" type="password" minlength="8" required></label><div class="actions"><button class="primary">Giriş yap</button></div><p id="authMsg" class="muted"></p></form></div>');
$('#report').insertAdjacentHTML('beforeend','<label>Araç / adres tespiti<select name="vehicleCheck"><option>Araç adreste bulundu</option><option>Araçlar adreste bulundu</option><option>Araç bulunamadı</option></select></label><label>Adres teyidi<select name="locationCheck"><option>Adres komşudan teyit edildi</option><option>Adres muhtardan teyit edildi</option><option>Adres teyit edilemedi</option></select></label><label>Ödeme durumu<select name="paymentStatus"><option>Ödeme yapma durumu yok</option><option>Ödeme yaptı</option><option>Ödeme yapacak</option><option>Fiili hacze gelinsin</option></select></label><label>Ödeme tutarı (₺)<input name="paymentAmount" type="number" min="0" step="0.01" value="0"></label><label>Ödeme sözü tarihi<input name="promiseDate" type="date"></label>');
const esc=v=>String(v??'—').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));const pill=s=>`<span class="pill ${s==='Tamamlandı'?'done':s==='Tekrar keşif'?'retry':''}">${esc(s)}</span>`;
function go(v){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));$('#'+v).classList.add('active');document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===v));if(v==='dashboard')dashboard();if(v==='tasks')tasks()}
function dashboard(){$('#total').textContent=records.length;$('#today').textContent=records.filter(x=>x.date===today).length;$('#done').textContent=records.filter(x=>x.status==='Tamamlandı').length;$('#retry').textContent=records.filter(x=>x.status==='Tekrar keşif').length;$('#upcoming').innerHTML=records.slice(0,6).map(x=>`<div class="case"><div><span class="label">${x.date} · ${esc(x.office)}</span><h3>${esc(x.number)} · ${esc(x.debtor)}</h3><p>${esc(x.address)}</p></div>${pill(x.status)}</div>`).join('')||'<div class="empty">Henüz görev yok.</div>'}
function tasks(){let date=$('#taskDate').value||today;$('#taskDate').value=date;let list=records.filter(x=>x.date===date);$('#taskList').innerHTML=list.length?`<div class="table-wrap"><table><thead><tr><th>İcra Dairesi</th><th>Dosya No</th><th>Borçlu Ünvanı</th><th>Bakiye</th><th>Service ID</th><th>Müşteri No</th><th>Adres</th><th>Plakalar</th><th></th></tr></thead><tbody>${list.map(x=>`<tr><td>${esc(x.office)}</td><td>${esc(x.number)}</td><td>${esc(x.debtor)}</td><td>${esc(x.balance)}</td><td>${esc(x.serviceId)}</td><td>${esc(x.customerNo)}</td><td>${esc(x.address)}</td><td>${esc(x.plates)}</td><td><button class="primary" onclick="detail('${x.id}')">Keşfe başla</button></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Bu tarih için atanan keşif dosyası yok.</div>'}
function detail(id){let x=records.find(x=>x.id===id);$('#dDate').textContent=x.date+' · '+x.office;$('#dTitle').textContent=x.number+' · '+x.debtor;$('#dAddress').textContent=x.address;$('#detailInfo').innerHTML=[['Bakiye',x.balance],['Service ID',x.serviceId],['Müşteri No',x.customerNo],['Plakalar',x.plates]].map(r=>`<tr><th>${r[0]}</th><td>${esc(r[1])}</td></tr>`).join('');$('#report [name=id]').value=id;go('detail')}window.detail=detail;
async function load(){let {data,error}=await db.from('kesif_dosyalari').select('*').order('kesif_tarihi');if(error)return alert(error.message);records=data.map(x=>({id:x.id,date:x.kesif_tarihi,office:x.icra_dairesi,number:x.dosya_no,debtor:x.borclu_unvani,balance:x.bakiye,serviceId:x.service_id,customerNo:x.musteri_no,address:x.adres,plates:x.plakalar,status:x.durum}));dashboard();tasks()}
async function ready(session){me=session.user;let p=await db.from('profiles').select('*').eq('id',me.id).single();if(p.error)return $('#authMsg').textContent=p.error.message;profile=p.data;$('#auth').remove();if(profile.role!=='yonetici'){document.querySelectorAll('[data-view="add"],[data-view="bulk"],[data-view="users"],[data-go="add"],[data-go="bulk"]').forEach(x=>x.style.display='none')}else{await loadUsers()}await load()}

async function loadUsers(){let u=await db.from('profiles').select('id,full_name,role,created_at').order('full_name');if(u.error)return alert(u.error.message);let options=u.data.map(x=>`<option value="${x.id}">${esc(x.full_name)} (${x.role})</option>`).join('');$('[name=assignee]').outerHTML=`<select name="assignee">${options}</select>`;$('#bulkPerson').innerHTML=options;$('#bulkDate').value=today;$('#userList').innerHTML=`<table><thead><tr><th>Ad</th><th>Rol</th><th>Oluşturulma</th></tr></thead><tbody>${u.data.map(x=>`<tr><td>${esc(x.full_name)}</td><td>${esc(x.role)}</td><td>${new Date(x.created_at).toLocaleDateString('tr-TR')}</td></tr>`).join('')}</tbody></table>`}
$('#authForm').onsubmit=async e=>{e.preventDefault();let d=Object.fromEntries(new FormData(e.target)),r=await db.auth.signInWithPassword(d);if(r.error)return $('#authMsg').textContent=r.error.message;ready(r.data.session)};
document.querySelectorAll('[data-view]').forEach(x=>x.onclick=()=>{go(x.dataset.view);if(x.dataset.view==='users')loadUsers()});document.querySelectorAll('[data-go]').forEach(x=>x.onclick=()=>go(x.dataset.go));$('#taskDate').onchange=tasks;
$('#userForm').onsubmit=async e=>{e.preventDefault();let d=Object.fromEntries(new FormData(e.target)),r=await db.functions.invoke('create-user',{body:d});if(r.error)return alert(r.error.message);e.target.reset();await loadUsers();alert('Kullanıcı oluşturuldu.')};
$('#xlsxFile').onchange=async e=>{let f=e.target.files[0];if(!f)return;let wb=XLSX.read(await f.arrayBuffer(),{type:'array'}),sheet=wb.Sheets[wb.SheetNames[0]];$('#csv').value=XLSX.utils.sheet_to_csv(sheet)};
document.querySelector('.tabs').insertAdjacentHTML('beforeend','<button data-view="reports" id="reportTab">Raporlar</button>');document.querySelector('.app').insertAdjacentHTML('beforeend','<section id="reports" class="view"><div class="panel"><h2>Ödeme raporları</h2><div class="cards"><div class="card"><span class="label">Bugün</span><b id="payDay">₺0</b></div><div class="card"><span class="label">Bu hafta</span><b id="payWeek">₺0</b></div><div class="card"><span class="label">Bu ay</span><b id="payMonth">₺0</b></div></div><div id="resultSummary" class="notice"></div></div></section>');$('#reportTab').onclick=async()=>{go('reports');let r=await db.from('kesif_sonuclari').select('odeme_tutari,completed_at,adres_sonucu,odeme_durumu');if(r.error)return alert(r.error.message);let now=new Date(),startDay=new Date(now.getFullYear(),now.getMonth(),now.getDate()),startWeek=new Date(startDay);startWeek.setDate(startDay.getDate()-((startDay.getDay()+6)%7)),startMonth=new Date(now.getFullYear(),now.getMonth(),1),sum=s=>r.data.filter(x=>new Date(x.completed_at)>=s).reduce((n,x)=>n+Number(x.odeme_tutari||0),0),fmt=n=>new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY'}).format(n);$('#payDay').textContent=fmt(sum(startDay));$('#payWeek').textContent=fmt(sum(startWeek));$('#payMonth').textContent=fmt(sum(startMonth));let grouped=r.data.reduce((a,x)=>{let k=x.adres_sonucu||'Sonuç yok';a[k]=(a[k]||0)+1;return a},{});$('#resultSummary').textContent='Sonuç dağılımı: '+Object.entries(grouped).map(([k,v])=>k+': '+v).join(' · ')};
$('#addForm').onsubmit=async e=>{e.preventDefault();if(profile.role!=='yonetici')return;let d=Object.fromEntries(new FormData(e.target));let r=await db.from('kesif_dosyalari').insert({kesif_tarihi:d.date,icra_dairesi:d.office,dosya_no:d.number,borclu_unvani:d.debtor,bakiye:d.balance||null,service_id:d.serviceId,musteri_no:d.customerNo,adres:d.address,plakalar:d.plates,atanan_personel:d.assignee});if(r.error)return alert(r.error.message);e.target.reset();await load();go('tasks')};
$('#report').onsubmit=async e=>{e.preventDefault();let d=Object.fromEntries(new FormData(e.target)),status=d.status==='Bulunamadı'?'Tekrar keşif':'Tamamlandı';let a=await db.from('kesif_dosyalari').update({durum:status}).eq('id',d.id),b=await db.from('kesif_sonuclari').upsert({dosya_id:d.id,adres_sonucu:d.status,mal_tespiti:d.asset,arac_durumu:d.vehicleCheck,adres_teyidi:d.locationCheck,odeme_durumu:d.paymentStatus,odeme_tutari:Number(d.paymentAmount||0),odeme_sozu_tarihi:d.promiseDate||null,notlar:d.note});if(a.error||b.error)return alert((a.error||b.error).message);await load();go('tasks')};
$('#import').onclick=async()=>{if(profile?.role!=='yonetici')return alert('Toplu ekleme yalnızca yöneticiler içindir.');let lines=$('#csv').value.trim().split(/\r?\n/).filter(Boolean),date=$('#bulkDate').value,assigned=$('#bulkPerson').value;if(!date||!assigned)return alert('Keşif tarihini ve personeli seçin.');let first=lines[0]?.toLocaleLowerCase('tr')||'',start=(first.includes('ünvan')||first.includes('unvan')||first.includes('müsteri')||first.includes('müşteri'))?1:0;if(lines.length<=start)return alert('Excel CSV satırlarını yapıştırın.');let items=[];for(let line of lines.slice(start)){let v=line.split(',').map(x=>x.trim());if(v.length<8)continue;let [debtor,customerNo,office,number,balance,serviceId,address,plates]=v;items.push({kesif_tarihi:date,icra_dairesi:office,dosya_no:number,borclu_unvani:debtor,bakiye:balance||null,service_id:serviceId,musteri_no:customerNo,adres:address,plakalar:plates,atanan_personel:assigned})}if(!items.length)return alert('Geçerli satır bulunamadı.');let result=await db.from('kesif_dosyalari').insert(items);if(result.error)return alert(result.error.message);$('#csv').value='';await load();go('tasks');alert(items.length+' dosya başarıyla atandı.')};$('#downloadTemplate').onclick=()=>{let a=document.createElement('a');a.href='data:text/csv;charset=utf-8,Adı/Ünvanı,Müşteri No,İcra Dairesi,Dosya No,Bakiye,Servis Dosya ID,Adres,Araç Plakaları%0AÖrnek Firma,7290586744,İstanbul 8. İcra Dairesi,2024/35058,20272.48,15301885636548,Başakşehir İstanbul,34 ABC 123';a.download='kesif-sablon.csv';a.click()};
(async()=>{let {data:{session}}=await db.auth.getSession();if(session)ready(session)})();
